language: java
jdk:
- openjdk7
deploy:
  provider: heroku
  api_key:
    secure: WyBwGOBy0s9H/ZyGQLTdh+LGoZMqlLYgJpay5adfvratsx5XTR6fh+5p6sjkDoRKEh9/d7F1fjtYG5+LuHd0Xb1nAGYhn2R89yRu9tSr86D/t1M7Z2bQy+MU/kFmPh/Ci//JsEHMBV48km1Bw+Pd8hZhYppE/mORFGj4jZ6uOHo=
  app: breakingbits-staging
  on:
    repo: BreakingBits/TicTacToe

#script:
#- sh bin//selenium_test_xvfb
#after_success:
#- echo "STAGING looks good you should promote to PRODUCTION"
install:
# Get Xvfb and Firefox
#- sudo apt-get install -y xvfb firefox
- sudo apt-get -y install x-ttcidfont-conf
# Install Xvfb packages
- sudo apt-get install -y xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic

after_script:
- export STAGING_SERVER=http://http://breakingbits-staging.herokuapp.com/
- sh bin/selenium_test_xvfb
- echo "STAGING looks good you should promote to PRODUCTION"


