language: java
jdk:
- oraclejdk7
- openjdk7
deploy:
  provider: heroku
  api_key:
    secure: WyBwGOBy0s9H/ZyGQLTdh+LGoZMqlLYgJpay5adfvratsx5XTR6fh+5p6sjkDoRKEh9/d7F1fjtYG5+LuHd0Xb1nAGYhn2R89yRu9tSr86D/t1M7Z2bQy+MU/kFmPh/Ci//JsEHMBV48km1Bw+Pd8hZhYppE/mORFGj4jZ6uOHo=
  app: breakingbits-staging
  on:
    repo: BreakingBits/TicTacToe

script:
- sh .//bin//selenium_test_xvfb
after_success:
- export PRODUCTION_SERVER=http://breakingbits-production.herokuapp.com/


