language: java
jdk: openjdk7
deploy:
  provider: heroku
  api_key:
    secure: WyBwGOBy0s9H/ZyGQLTdh+LGoZMqlLYgJpay5adfvratsx5XTR6fh+5p6sjkDoRKEh9/d7F1fjtYG5+LuHd0Xb1nAGYhn2R89yRu9tSr86D/t1M7Z2bQy+MU/kFmPh/Ci//JsEHMBV48km1Bw+Pd8hZhYppE/mORFGj4jZ6uOHo=
  app: breakingbits-staging
  on:
    repo: BreakingBits/TicTacToe

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"

install:
- "sudo apt-get install -y xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic"

after_script:
- "sh bin/after_script"
- status=$?
- "sh -e /etc/init.d/xvfb stop"
- if [ $status -eq 0 ] then; "sh bin/prod_server"; else "echo Selenium tests failed. Deployment stopped"; fi